# Generated by Django 5.1.1 on 2025-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_order_shippingaddress_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=200, verbose_name='Lastname of customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(default='', max_length=200, verbose_name='Name of customer'),
        ),
    ]
